In [1]:
import torch
import numpy as np

# initializating a tensor

In [11]:
# directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"x_data: \n{x_data}")
print(f"x_np: \n{x_np}")

x_data: 
tensor([[1, 2],
        [3, 4]])
x_np: 
tensor([[1, 2],
        [3, 4]])


In [12]:
# from another tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"x_ones: \n{x_ones}")
print(f"x_rand: \n{x_rand}")

x_ones: 
tensor([[1, 1],
        [1, 1]])
x_rand: 
tensor([[0.5248, 0.5928],
        [0.3341, 0.7607]])


In [16]:
# with random or cnstant values
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"rand_tensor: \n{rand_tensor}" )
print(f"ones_tensor: \n{ones_tensor}")
print(f"zeros_tensor: \n{zeros_tensor}")

rand_tensor: 
tensor([[0.4705, 0.3848, 0.9541],
        [0.1362, 0.7309, 0.7738]])
ones_tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# attributes of a tensor

In [17]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


# operations on tensors

In [ ]:
# データをCPU -> GPUへ転送
## これが一番モダンな書き方
tensor = torch.rand(3,4)  # cpu
print(tensor.device)
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(tensor.device)  # mps:0

## いつも見る書き方
tensor = torch.rand(3,4)  # cpu
print(tensor.device)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = tensor.to(device)
print(tensor.device)  # cpu(MACにはgpuはないため)

device = "mps" if torch.mps.is_available() else "cpu"
tensor = tensor.to(device)
print(tensor.device)  # mps:0(MACにはmpsはあるため)

cpu
mps:0
cpu
cpu
mps:0


In [45]:
tensor = torch.ones(4,4)
print(tensor)
print(f"first raw: {tensor[0]}")
print(f"first column: {tensor[:, 0]}")
print(f"last column: {tensor[..., -1]}")  # tensor[..., -1] is the same as tensor[:, :, -1]

tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first raw: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [46]:
torch.cat([tensor, tensor], dim=1)
# torch.cat([tensor, tensor])

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [47]:
# 行列積(Matri Multipication)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)  # 事前に作った箱（y3）に入れる。メモリ節約
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [48]:
# 要素積(Elementwise Product)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [49]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()  # convert single element tensor to a python float
print(agg_item)

tensor(12.)
12.0


In [ ]:
# in-place operations(直接書き換え。メモリを新たに食わない)
# けどbackpropargation中にコレをやるとエラーの原因になるのでやらないのが無難
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# bridge with numpy

In [51]:
# tensor to numpy array
t = torch.ones(5)
print(f"tensor: {t}")
n = t.numpy()
print(f"numpy array: {n}")

tensor: tensor([1., 1., 1., 1., 1.])
numpy array: [1. 1. 1. 1. 1.]


In [52]:
# a change in the tensor refletcts in the numpy array
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [53]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# additional problems from gemini

In [ ]:
# broadcasting
a = torch.rand(3,1)
b = torch.rand(1,4)
c = a + b
print(c.shape)  # (3,1)と(1,4)は互いに拡張されるので、結果は(3,4)となる

torch.Size([3, 4])


In [58]:
# flatten
images = torch.rand(8, 1, 28, 28)
print(images.shape)
flattened_images = images.view(8, -1)
print(flattened_images.shape)

flattened_images2 = torch.flatten(images, start_dim=1)
print(flattened_images2.shape)

torch.Size([8, 1, 28, 28])
torch.Size([8, 784])
torch.Size([8, 784])


In [62]:
# mask
tensor = torch.randn(5,5)
print(tensor)
tensor[tensor < 0] = 0
print(tensor)

tensor([[ 1.3374, -1.5021, -2.0084,  0.5415, -0.7715],
        [ 0.9357, -0.0191, -0.5213, -0.6193, -0.6631],
        [ 1.6045,  1.2302, -1.1505,  0.1005,  1.5484],
        [-0.1342,  0.5002, -1.9671, -0.8642, -0.8510],
        [-0.9521, -0.9772, -1.4842, -0.3260,  0.9524]])
tensor([[1.3374, 0.0000, 0.0000, 0.5415, 0.0000],
        [0.9357, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.6045, 1.2302, 0.0000, 0.1005, 1.5484],
        [0.0000, 0.5002, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.9524]])


In [63]:
# permute
img_torch = torch.rand(3, 100, 100)  # C, H, W
img_torch = img_torch.permute(1, 2, 0)  # H, W, C
print(img_torch.shape)


torch.Size([100, 100, 3])
